import {
  TILED_LAYER_COIN,
  TILED_LAYER_TRAP,
  TILED_LAYER_BLOCK,
  TILED_LAYER_PIPE,
  TILED_LAYER_FLAGPOLE,
  TILED_LAYER_LAND,
  TILED_LAYER_MOUNTAIN,
  TILED_LAYER_CLOUD,
  TILED_LAYER_BACKGROUND,
  TILED_LAYER_MAP,
  TILED_OBJECT_OTHERS,
  TILED_OBJECT_MUSHROOM,
  TILED_OBJECT_ENEMY,
  TILED_OBJECT_MAP,
  OBJECT_OTHERS_BIRTH_POINT,
  OBJECT_OTHERS_FLAG_POINT,
  OBJECT_MUSHROOM_REWARD,
  OBJECT_MUSHROOM_ADDLIFE,
  OBJECT_ENEMY_MUSHROOM,
  OBJECT_ENEMY_FLOWER,
  OBJECT_ENEMY_TORTOISE,
  OJECT_OTHERS_MAP,
  OBJECT_MUSHROOM_MAP,
  OBJECT_ENEMY_MAP,
} from "../Common/constant";
export default class TiledMapData {
  public static TILED_LAYER_COIN = TILED_LAYER_COIN;
  public static TILED_LAYER_TRAP = TILED_LAYER_TRAP;
  public static TILED_LAYER_BLOCK = TILED_LAYER_BLOCK;
  public static TILED_LAYER_PIPE = TILED_LAYER_PIPE;
  public static TILED_LAYER_FLAGPOLE = TILED_LAYER_FLAGPOLE;
  public static TILED_LAYER_LAND = TILED_LAYER_LAND;
  public static TILED_LAYER_MOUNTAIN = TILED_LAYER_MOUNTAIN;
  public static TILED_LAYER_CLOUD = TILED_LAYER_CLOUD;
  public static TILED_LAYER_BACKGROUND = TILED_LAYER_BACKGROUND;
  public static TILED_LAYER_MAP = TILED_LAYER_MAP;
  public static TILED_OBJECT_OTHERS = TILED_OBJECT_OTHERS;
  public static TILED_OBJECT_MUSHROOM = TILED_OBJECT_MUSHROOM;
  public static TILED_OBJECT_ENEMY = TILED_OBJECT_ENEMY;
  public static TILED_OBJECT_MAP = TILED_OBJECT_MAP;
  public static OBJECT_OTHERS_BIRTH_POINT = OBJECT_OTHERS_BIRTH_POINT;
  public static OBJECT_OTHERS_FLAG_POINT = OBJECT_OTHERS_FLAG_POINT;
  public static OBJECT_MUSHROOM_REWARD = OBJECT_MUSHROOM_REWARD;
  public static OBJECT_MUSHROOM_ADDLIFE = OBJECT_MUSHROOM_ADDLIFE;
  public static OBJECT_ENEMY_MUSHROOM = OBJECT_ENEMY_MUSHROOM;
  public static OBJECT_ENEMY_FLOWER = OBJECT_ENEMY_FLOWER;
  public static OBJECT_ENEMY_TORTOISE = OBJECT_ENEMY_TORTOISE;
  public static OJECT_OTHERS_MAP = OJECT_OTHERS_MAP;
  public static OBJECT_MUSHROOM_MAP = OBJECT_MUSHROOM_MAP;
  public static OBJECT_ENEMY_MAP = OBJECT_ENEMY_MAP;
}
